CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".austin_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".austin_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".charlotte_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".chicago_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".cincinnatti_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".colorado_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".colorado_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".dallas_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".dallas_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".houston_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".houston_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".kansas_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".kansas_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".kansas2_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".la_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".la_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".lafc_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".lafc_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".miami_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".minnesota_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".minnesota_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".nashville_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".orlando_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".portland_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".portland_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".salt_lake_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".salt_lake_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".san_jose_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".san_jose_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".seattle_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".seattle_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".toronto_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".vancouver_away_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);

CREATE TABLE IF NOT EXISTS "CITY_game_pass_types_data".vancouver_home_pass_types
(
    "Player_#" integer NOT NULL,
    "Player" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "Nation" character varying(50) COLLATE pg_catalog."default" NOT NULL,
    "Position" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Age" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    "Full_90_Played" numeric NOT NULL,
    "Pass_Attempts" integer NOT NULL,
    "Live_Ball_Passes" integer NOT NULL,
    "Dead_Ball_Passes" integer NOT NULL,
    "Free_Kick_Passes" integer NOT NULL,
    "Through_Balls" integer NOT NULL,
    "Switches" integer NOT NULL,
    "Crosses" integer NOT NULL,
    "Throw_Ins" integer NOT NULL,
    "Corner_Kicks" integer NOT NULL,
    "In_Swinging_Corners" integer NOT NULL,
    "Out_Swinging_Corners" integer NOT NULL,
    "Straight_Corners" integer NOT NULL,
    "Passes_Completed" integer NOT NULL,
    "Passes_Offside" integer NOT NULL,
    "Passes_Blocked" integer NOT NULL,
    CONSTRAINT city_season_pass_types_pkey PRIMARY KEY ("Player #")
);